name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        container: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to latest version

      - name: Set up Node.js
        uses: actions/setup-node@v4  # Updated to latest version
        with:
          node-version: '20'  # Updated to a more recent LTS version

      - name: Install dependencies
        run: |
          cd core
          npm install

      - name: Run Cypress tests in parallel
        run: |
          cd core
          npm run test

      - name: Upload Cypress videos and screenshots
        if: always()
        uses: actions/upload-artifact@v4  # Updated from v3 to v4
        with:
          name: cypress-artifacts
          path: |
            core/cypress/videos
            core/cypress/screenshots
